/**
 * \file ProjectDefinition.hpp
 * \brief Project definition
 * \author Diego Iastrubni diegoiast@gmail.com
 */

// SPDX-License-Identifier: MIT

#pragma once

#include <QHash>
#include <QString>

[[maybe_unused]] auto constexpr PLATFORM_LINUX = "linux";
[[maybe_unused]] auto constexpr PLATFORM_WINDOWS = "windows";
[[maybe_unused]] auto constexpr PLATFORM_MACOS = "macos";

#if defined(_WIN32)
auto constexpr PLATFORM_CURRENT = PLATFORM_WINDOWS;
#elif defined(linux)
auto constexpr PLATFORM_CURRENT = PLATFORM_LINUX;
#elif defined(__APPLE__)
auto constexpr PLATFORM_CURRENT = PLATFORM_MACOS;
#endif

/*
 * Each project will have a list of executables it is assigned to build/create.
 * Each project will have a list of tasks build (usually) an executable.
 *
 * Note that each platform will have different list of tasks and executables.
 *
 * Tasks are defined per platform host - as they are to be executed "locally".
 * Executables are not exactly tied to the running platform. As we might cross build
 * or those can be platform indipendent scripts (not
 *
 */

struct ExecutableInfo {
    QString name;
    QString runDirectory;
    QHash<QString, QString> executables;

    bool operator==(const ExecutableInfo &other) const;
};

struct TaskInfo {
    QString name;
    QString tooltip;
    QString runDirectory;

    // This is used to note a build. Usually completion is rescanned after a good build
    bool isBuild = false;

    // key: platform, value: list of commands
    QHash<QString, QStringList> commands;

    bool operator==(const TaskInfo &other) const;

    // Compute tooltip, according to current platform
    QString getTooltip() const;
};

enum class ProjectType { cmake, cargo, golang, meson, unknown };

struct ProjectDefinition {
    ProjectDefinition() = default;
    QString sourceDir;
    QString buildDir;
    QString hideFilter;
    QList<ExecutableInfo> executables;
    QList<TaskInfo> tasksInfo;

    // meta data
    bool autoGenerated = true;
    ProjectType projectType = ProjectType::unknown;
    QString name;
    QString fileName;

    static std::shared_ptr<ProjectDefinition> tryGuessFromCMake(const QString &fileName);
    static std::shared_ptr<ProjectDefinition> tryGuessFromCargo(const QString &fileName);
    static std::shared_ptr<ProjectDefinition> tryGuessFromGo(const QString &fileName);
    static std::shared_ptr<ProjectDefinition> tryGuessFromMeson(const QString &fileName);
    static std::shared_ptr<ProjectDefinition> tryLoadFromCodePointer(const QString &jsonFileName);
    static QList<std::shared_ptr<ProjectDefinition>> findProjects(const QString &dirName);

    void updateBinariesCMake();
    void updateBinariesCargo();
    void updateBinariesGo();
    void updateBinariesMeson();
    void updateBinaries();

    void saveToFile(const QString &jsonFileName);
    const QHash<QString, QString> getConfigDictionary() const;
    bool operator==(const ProjectDefinition &other) const;
};
